theme = "monokai_pro_octagon"

[keys.insert]
"C-A-l" = ":fmt"
"C-k" = "toggle_comments"

[keys.normal]
"C-k" = "toggle_comments"
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
d = ["yank_main_selection_to_clipboard", "delete_selection"]

[keys.normal."z"]
"z" = ":w"

[keys.normal."Z"]
"Z" = ":wq"

[keys.select]
"C-k" = "toggle_comments"
y = "yank_main_selection_to_clipboard"
p = "replace_selections_with_clipboard"
P = "paste_clipboard_before"
d = ["yank_main_selection_to_clipboard", "delete_selection"]

[editor]

[editor.auto-save]
focus-lost = true

[editor.auto-save.after-delay]
enable = true
timeout = 1500
